### ISSUE TITLE
Use `adjoint` rather than defining `dagger`

### ISSUE THREAD

**Issue by jlapeyre** [Adgnitio/QuantumCircuits.jl#10]
Instead of this
https://github.com/Adgnitio/QuantumCircuits.jl/blob/fa10c8b8c25f160be368a86a938c39f8d0d3023c/src/QCircuits/Math.jl#L20-L21
you can use `adjoint`.   There is a lot of support for the wrapper type `Adjoint`.

**Comment by MozammilQ** [comment]
@jlapeyre , you mean 
dagger(x)=x'
Isn't it??

**Comment by jlapeyre** [comment]
`x'` is a notation for exactly `adjoint(x)`. This just wraps `x` in type `Adjoint`. The function is defined like this `adjoint(A::AbstractVecOrMat) = Adjoint(A)`.  Then the transpose and hermitian conjugates are performed lazily. A difference with `dagger(x) = transpose(conj(x))` is that the conjugate is done eagerly (causes allocation!) and then the `Transpose` wrapper is added with `transpose`. But, beyond this, it is a good idea in general not to repeat existing functionality. Also, there are functions (existing and in the future) that can take advantage of the lazy wrapper to improve efficiency. For example `adjoint(adjoin(x))`.

**Comment by jlapeyre** [comment]
> @jlapeyre , you mean
dagger(x)=x'
Isn't it??

I think I may have misunderstood this question. So, I'll answer the question as I understand it. Hope I don't misunderstand! No, I don't mean to define `dagger` in terms of `adjoint`. I mean it's best to not define `dagger` at all.  So instead of this
https://github.com/Adgnitio/QuantumCircuits.jl/blob/fa10c8b8c25f160be368a86a938c39f8d0d3023c/src/QCircuits/Math.jl#L48
you would have  `abs(tr(adjoint(mat) * mat))`.

But, as explained in #12, there is a much more efficient way to do `abs(tr(adjoint(mat) * mat))`, so we really need neither `dagger` nor `adjoint` (at least as far as QuantumCircuits.jl is currently developed.)

So this issue (#10) could be closed when #12 is closed. I made this one first.
