### ISSUE TITLE
`unitary_error` efficiency

### ISSUE THREAD

**Issue by jlapeyre** [Adgnitio/QuantumCircuits.jl#11]
`unitary_error` is defined with this
https://github.com/Adgnitio/QuantumCircuits.jl/blob/fa10c8b8c25f160be368a86a938c39f8d0d3023c/src/QCircuits/Math.jl#L24-L27
and this
https://github.com/Adgnitio/QuantumCircuits.jl/blob/fa10c8b8c25f160be368a86a938c39f8d0d3023c/src/QCircuits/Math.jl#L46-L49

A more efficient way to do this is
```julia
function myunitary_error(A, B)
    sum(((a,b),) -> abs2(a - b), zip(A,B))
end
```
The time and memory usage is found with
```julia
julia> A = rand(64, 64);

julia> B = rand(64, 64);

julia> @btime unitary_error($A, $B)
  28.194 μs (4 allocations: 64.09 KiB)
673.8939926865573

julia> @btime myunitary_error($A, $B)
  2.917 μs (0 allocations: 0 bytes)
673.8939926865586
```
Notice that `myunitary_error` does no allocation.

By the way, I can't find the equivalent code in Qiskit. Can you point me to it?

**Comment by rafal-pracht** [comment]
@jlapeyre I've changed the unitary error_function. Regarding the usage. This method is not inspired by Qiskit, it is needed to find the best parameter of the u4 gate when we would like to find the equivalence between the u4 and given 2 qubits circuit. Unitary error is a good candidate for loss function during optimization.
