### ISSUE TITLE
Avoid importing I from LinearAlgebra

### ISSUE THREAD

**Issue by jlapeyre** [Adgnitio/QuantumCircuits.jl#20]
This is not about correctness or efficiency. Opinions vary.

Here, I would avoid importing `I`.
https://github.com/Adgnitio/QuantumCircuits.jl/blob/42a906168fffe91aa259d458359ca414027df09a/src/QCircuits/Circuit.jl#L28

In general in library code, I (and others) recommend usually fully qualifying symbols.

One reason that you *would* want to import a symbol is if it is used in many places. But, in this case `I` is only used once.

`I` is used frequently in quantum code for the identity operator.

It is easier, when reading code, to know where the symbol is defined. This is especially true for symbols that are hard to search for, like `I`. The counter argument to this is that you should be using a smart editor that can give information on any symbol.

So you could do `import LinearAlgebra` at the top and then write `LinearAlgebra.I` in the one place that it is used. Another option is to consistently do `import LinearAlgebra as LinAlg` or `LA` or something like that. People do this in Python frequently. But, even there, you often see people use `numpy` instead of `np` in library code.

**Comment by rafal-pracht** [comment]
I've changed that.
