### ISSUE TITLE
use cis instead of exp(im .)

### ISSUE THREAD

**Issue by jlapeyre** [Adgnitio/QuantumCircuits.jl#23]
In general `cis(x)` is faster than `exp(im*x)`.

Here are some places this could be changed.

```julia
QCircuits/Gates.jl
246:# exp(-1im * θ/2) * u1matrix(θ)
247:Rzmatrix(θ) = [exp(-1im * θ/2) 0; 0 exp(1im * θ/2)]

QML/CircuitOptimization.jl
89:    lossPhase(params) = real(unitary_error(expmat, exp(1im * params[1]) * tomatrix(qc, params[2:end])))

QCircuits/Gates.jl
237:u3matrix(θ, ϕ, λ) = [cos(θ/2)+0im              -exp(1im * λ) * sin(θ/2);
238:                     exp(1im * ϕ) * sin(θ/2)   exp(1im * λ + 1im * ϕ) * cos(θ/2)]
247:Rzmatrix(θ) = [exp(-1im * θ/2) 0; 0 exp(1im * θ/2)]

```

**Comment by jlapeyre** [comment]
* You can see what happens by doing this
```julia
julia> m = rand(Complex{Float64}, 2, 2);

julia> @edit cis(m)
```
This shows that `im .* m` is created (a new matrix) and then an inplace function `exp!` is called. This is evidently the mutation that Zygote is complaining about. Might be worth opening an issue or asking a question on some Zygote forum.

* A couple of quick tests showed that the efficiency difference is not great. So it makes sense to take the efficiency gain since `cis` adds no complexity. But, if there is a little problem, like here, better to just let it go.

**Comment by jlapeyre** [comment]
I reopened this, because I forgot to mention something. `cis()` for square matrices (rather than numbers) is only supported for Julia v `>=1.7`. I'm not sure if there were other instances where you changed `exp` to `cis` where the argument was a matrix. If so, we need to restrict the Julia version in `[compat]` in Project.toml. Or else, use `exp(im * m)` in those cases. Or use an `if` -- `else` to, say, define `cis(m) = exp(im * m)` in case Julia version is less than 1.7.

**Comment by rafal-pracht** [comment]
This is only one place where we have a complex matrix as a parameter. So we can close the issue. Btw,  I've added CI which runs the test for Julia 1.6, 1.7, and night build before all PR. So if there will be any issue we will see it.  https://github.com/Adgnitio/QuantumCircuits.jl/pull/41
