### ISSUE TITLE
Having many functions as fields in a struct is problematic.

### ISSUE THREAD

**Issue by jlapeyre** [Adgnitio/QuantumCircuits.jl#28]
Defining many functions inside a struct, such as in
https://github.com/Adgnitio/QuantumCircuits.jl/blob/973a184a87a4252ab34bacbd7aea55596fd2cb52/src/QCircuits/Circuit.jl#L40
is not idiomatic Julia. It certainly is convenient to use this class-based OO notation. And it closely follows the Python interface.

Here are the first few of about 17 such functions implementing gate application
https://github.com/Adgnitio/QuantumCircuits.jl/blob/973a184a87a4252ab34bacbd7aea55596fd2cb52/src/QCircuits/Circuit.jl#L53-L58

I don't know what the semantics of functions as fields in a struct are, and can't find them documented. But, investigating, the behavior is not what I'd expect.  It seems that each time `QCircuit` is constructed new fields of type `Function` are *not* created. Rather, they are sort of static in the constructor. But, it's not clear to me whether each time `QCircuit` is constructed with many pointers. In Python,  methods are stored only in the class `__dict__`, not in the instance (unless overridden).

In any case, a bit of testing shows that using `getproperty` is faster, in a simpler case. It may be faster here as well. It's worth testing. 

That is, instead of making `cx` a field of `QCircuit` and doing `qc.cx = (c, t) -> add!(qc, CX, c, t)`,  you would omit the field `cx` from `QCircuit` and do
```julia
function Base.getproperty(qc::QCircuit, sym::Symbol)
    if sym === :cx
         return (c, t) -> add!(qc, CX, c, t)
   else if sym === :cz
      ....
   end
   return getfield(qc, sym)
end
```
The compiler seems to insert the function at compile time if `sym` is a literal symbol.

There might also be an advantage to adding, removing, changing gate-adding functions without changing the fields of the structs. That is, if you add a new gate, you have to change the struct. If you have serialized gates into a file, you can't read them into the new structs. But, if you use `getproperty`, you don't have this problem.

**Comment by LF-Flores** [comment]
There are no pointers created when an instance of a `QCircuit` struct is defined. The reason being that currently the functions being assigned to the Function fields (`x`, `sx`, etc...) are determined only once at compile time. To see it, note for example that in:

https://github.com/Adgnitio/QuantumCircuits.jl/blob/86d26f8a2578e92bf2843c018339f1cc12daa32b/src/QCircuits/Circuit.jl#L95-L99

all fields are assigned as anonymous functions which, if inside of another function (that is, as a closure), have consistent type throughout the parent's function calls (in this case, the constructor). Lets remember that anonymous functions have automatically generated types like `var"#11#12"` that differs for each function created, even if they are identical otherwise, but not in this case because of the closure.

That, with the fact that, when a call syntax is used, the Julia parser begins the dispatch process, for which it only matters the type of the variable that is being used in the call (in this case, the type of that anonymous function, e.g. `typeof(qc.x)`, `typeof(qc.sx)`, etc.). Read [here](https://docs.julialang.org/en/v1/devdocs/functions/#Julia-Functions) for more about that.

That means that when two instances of `QCircuit`, lets say `qc1` and `qc2` call the same Function field as `qc1.x(...)`, `qc2.x(...)`, the same type of variable is being used and thus, the same method is being dispatched from the [method table](https://docs.julialang.org/en/v1/devdocs/functions/#Method-Tables) without the need of pointers or the existence of "different" functions for each instance.

That said, I agree that is better to use `getproperty` if you really want that OOP syntax instead of having fields of type `Function`[^1], since, as you said, it's faster because the compiler is able to do [constant folding](https://en.wikipedia.org/wiki/Constant_folding), optimizing away every non-relevant branch when the syntax `a.b` is used.

If what you need is a complete refactoring of the current structs with `Function` fields into the respective `getproperty` definitions, I can begin to work on it if you want! 

[^1]: Which is in itself a performance issue, since `Function` is an abstract type, see [here](https://docs.julialang.org/en/v1/manual/performance-tips/#Avoid-fields-with-abstract-type)

**Comment by rafal-pracht** [comment]
@LF-Flores, it would be great if you can work on this.

I think that in getproperty function we can use the dictionary from symbol to lambda. In that case, the function will be quite small and any maintenance will be only by putting new entries to the dictionary.

**Comment by jlapeyre** [comment]
There is (probably) an important problem. The type `Dict` is mutable, so there is no way to optimize the call during compile time. If I recall, I tested and found that `if sym === :cx` , etc. is evaluated and a branch taken at compile time, if the call `circ.cx` is literal. This could include `circ.qubit` (But, this last example could be special cased.) So you should be careful about testing performance before deciding.  You might try...

* A circuit manipulation macro, like `@circ circ.h(2)`. You could add some DSL-like behavior as well.
* You can probably make a macro that the programmer uses, not the user. This would look up in the `Dict` at compile time.
* I'm sure people have tried similar things. There may be existing packages. In fact, I know there are at least one or two. But, I don't think they are widely used. One of the authors explicitly stated that he wrote it just to show it could be done, not because he thought it would be good practice to use it.

**Comment by jlapeyre** [comment]
So people have done quite a bit of talking and thinking about this. I think the best solution may be to either just use `add!` or try something that is more idiomatic Julia. You may make `QCircuit` callable, so that you can do `circuit(h(0))`, or
```julia
circuit(h(0), h(1), cx(0, 1))
```
This is simple, uses no macro (i.e. mini-language), and adds few extra keystrokes. A disadvantage is that it requires importing the gate functions `x`, etc.  These have short names, so importing `x` is error prone. Also you have to import it into any lexical scope, whereas `circ.x(0)` works anywhere.

A partial solution is `import Gates as G`, and then `G.x(0)`. Not very pretty either.

Again a macro. Maybe
```julia
circuit = QCircuit(...)
i = 10
@gates circuit begin
   h(i),
   h(i+1),
   cx(i, i+1),
end
```
That doesn't seem quite right, but maybe something like it.

**Comment by jlapeyre** [comment]
I've thought some more about this. I think maintaining and extending the module will be easier and simpler if it is done using idiomatic Julia coding. That is no tricks in the module itself with `getproperty`. Then special syntax can be added with macros, or string macros.

I think one of the most important points (or the most) is to avoid importing functions like `x()`, as I said above. Requiring 100 gates, many of them one character long, in your namespace so that you can do `circuit(h(0), h(1), cx(0, 1))` would be trouble. Of course, some of qiskit (eg, opflow) already makes you import `X`, `H` etc. if you want to use them. But, at least `X` is a capital letter. Disallowing `x` as a variable everywhere (because it's a function) would be unfortunate.

Here is a quick (working) sketch of how this might be done. First a toy circuit module
```julia
module QCircuits

struct Circuit
    numqubits::Int
end

function add!(args...)
    println("add! got ", length(args), " args: ", args)
end

x(args...) = (:x, args)
cx(args...) = (:cx, args)
h(args...) = (:h, args)

end # module QCircuits
```

Below I define a macro so that these work:
```julia
acirc = QCircuits.Circuit(2)

# Specify the circuit as the first argument
@gate acirc acirc.h(0)

# Get the circuit from the only expression
@gate acirc.x(0)

# This is not transformed because it doesn't match a function call
# So it works as intended.
@gate acirc.numqubits

# Specify the circuit
@gate acirc begin
    acirc.x(0)
    acirc.cx(0, 1)
end

# Get the circuit from the first expression in the block
@gate begin
    acirc.x(0)
    acirc.cx(0, 1)
    println("num qubits: ", acirc.numqubits)
end
```

The following code implements the examples above.  (It should be written with more clarity.) (Debugging print statements are included.)
```julia
using MacroTools

function dobody(incirc, ex)
    MacroTools.postwalk(x -> @capture(x, circ_.f_(args__)) && circ === incirc ?
        begin
           :(QCircuits.add!($circ, QCircuits.$f($(args...))))
        end
          : x, ex)
end

macro gate(gbody)
    @capture(gbody, circ_.f_(args__))
    if circ != nothing
        result = :(QCircuits.add!($circ, QCircuits.$f($(args...))))
        println(result)
        return result
    end
    rmbody = MacroTools.rmlines(gbody)
    if MacroTools.isexpr(rmbody, :block)
        ex1 = rmbody.args[1]
        @capture(ex1, circ_.f_(args__))
        if circ != nothing
            res = dobody(circ, gbody)
            println(res)
            return res
        end
    end
    return gbody
end

macro gate(circ, gbody)
    res = dobody(circ, gbody)
    println(res)
    return res
end
```

Some improvments you could make are
* Add code in the macro to check the type of `acirc` and do the transformation if it is of type `Circuit`. This would be compiled and have zero runtime cost. Then you could do things like this
```julia
acirc = QCircuits.Circuit(2)
bcirc = QCircuits.Circuit(3)
@gate begin
    acirc.x(0)
    bcirc.h(2)
end
```

If you restrict the semantics inside `@gate`, you could do a more qasm-like thing instead. For example
```julia
@gate acirc begin
    x(0)
    h(1)
    cx(0, 1)
end
```
In this case all gates would be applied to `acirc`. You would either assume that every function call in the block is a gate, or compare to a list of function calls.

* Another possibility that would be even easier to write as a macro would make the following work. `@circ acircuit(x(0), cx(0, 1))`. This would add gates `x` and `cx` to circuit `acircuit`. Again, you would not need to import `x` and `cx`.

**Comment by jlapeyre** [comment]
Here is what the more qasm-like macro looks like
```julia
macro circ(incirc, ex)
  MacroTools.postwalk(ex) do x
      (@capture(x, f_(args__)) && f != :(QCircuits.add!)) || return x
      expr = :(QCircuits.add!($incirc, QCircuits.$f($(args...))))
      println(expr)
      return expr
  end
end
```
Then this input (using the module definition above)
```julia
acirc = QCircuits.Circuit(2)

@circ acirc begin
    i = 0
    j = 1

    h(i)
    h(j)
    cx(i, j)
end
```
outputs this:
```julia
QCircuits.add!(acirc, QCircuits.h(i))
QCircuits.add!(acirc, QCircuits.h(j))
QCircuits.add!(acirc, QCircuits.cx(i, j))
add! got 2 args: (Main.QCircuits.Circuit(2), (:h, (0,)))
add! got 2 args: (Main.QCircuits.Circuit(2), (:h, (1,)))
add! got 2 args: (Main.QCircuits.Circuit(2), (:cx, (0, 1)))
```
This is maybe a bit fragile because it interprets any function call other than `add!` as a gate.

**Comment by rafal-pracht** [comment]
I like the macro version. It looks similar to Qiskit's code, and this was the main idea of the design. I will rewrite it. Thanks for your hint.

**Comment by jlapeyre** [comment]
With the above definition of `@circ`, the following fails (because `+` is a function)
```julia
@circ acirc begin
    i = acirc.numqubits - 1
    j = i + 1

    h(i)
    h(j)
    cx(i, j)
end
```
However, this example does work if we use the following definition of `@circ`
```julia
const GateList = (:x, :h, :cx)

macro circ(incirc, ex)
  MacroTools.postwalk(ex) do x
      (@capture(x, f_(args__)) && f in GateList) || return x
      expr = :(QCircuits.add!($incirc, QCircuits.$f($(args...))))
      println(expr)
      return expr
  end
end
```
This  appears much more robust, but still requires some more thought: This would require a function to register gates so that they are added to `GateList`. Moreover, this lookup of gates in `GateList` happens at compile time, not runtime.

**Comment by jlapeyre** [comment]
@rafal-pracht  Yes, I like the macro version better the more I look at it. One advantage is that it decouples the design of `QCircircuit` and related code from the design of the convenience interface.

Also note that, regardless of what kind of macro behavior you want, the way that`@circ` is written above is cleaner than the first macros that I wrote in the first comments. The macros for `@circ` follow a pattern recommended in the docs for MacroTools.

**Comment by rafal-pracht** [comment]
@jlapeyre, I've implemented the first version of the code: https://github.com/rafal-pracht/QuantumCircuits.jl/tree/struct_functions%2328

I've used both macros @ gate and @ circuits because they complement each other: https://github.com/rafal-pracht/QuantumCircuits.jl/blob/struct_functions%2328/src/QCircuits/Circuit.jl#L308-L360

The @ gate allows us to do all that previously we can do with in structure functions. But putting @ gate at the beginning of each line is ugly (the function way was more beautiful): https://github.com/rafal-pracht/QuantumCircuits.jl/blob/struct_functions%2328/test/QCircuits/CircuitMacroTest.jl#L36-L42

Form the other hand, for @ circuit macro, I decided to not escape the variable out of macro scope (and I think this is correct behavior) but this rais an issue when I would like to access to the number of qubits or register. So the code below doesn't work.
```julia
acirc = QCircuit(5)
@circ acirc begin
    n = acirc.qubits #TODO this doesn't works
    foreach(i -> h(i), 0:n)
    foreach(i -> cx(i, i+1), 0:n-1)
end
```
and this also
```julia
qr11 = QuantumRegister(1)
qr12 = QuantumRegister(1)
qc1 = QCircuit([qr11, qr12])
@circ qc1 begin
    x(qr11[0])
    h(qr12[0])
end
```
Do you have any hints?

**Comment by jlapeyre** [comment]
Do you want to allow users to define gates ? 

If so, [this looks problematic](https://github.com/rafal-pracht/QuantumCircuits.jl/blob/8ca42bbba56a1ed33b3775d05660aedd0fff9935/src/QCircuits/Circuit.jl#L330)
```julia
const GateList = (:x, :sx, :y, :z, :h, :cx, :s, :sdg, :t, :tdg, :u, :u3, :rx, :ry, :rz, :rzx, :u4)
```
A solution might be to manage a list of gates. A user has to somehow register a new gate (where is this stored?) Then the new gate can be used in a macro.

**Comment by jlapeyre** [comment]
> I decided to not escape the variable out of macro scope

Did you try this? It might make the broken examples work. And maybe not break anything more.

**Comment by jlapeyre** [comment]
> the function way was more beautiful

Yes, the simple syntax is nice.

**Comment by jlapeyre** [comment]
I can get these examples to work:
```julia
qr11 = QuantumRegister(1)
qr12 = QuantumRegister(1)
qc1 = QCircuit([qr11, qr12])
@circ qc1 begin
    x(qr11[0])
    h(qr12[0])
end

acirc = QCircuit(5)
@circ acirc begin
    n = acirc.qubits #TODO this doesn't works
    foreach(i -> h(i), 0:n)
    foreach(i -> cx(i, i+1), 0:n-1)
end
```
with this change to the macro

```julia
macro circ(incirc, ex)
    # bind the circuilt variable
    incirc = esc(incirc)

    MacroTools.postwalk(ex) do x
        if !(@capture(x, f_(args__)) && f in GateList)
            return esc(x) == incirc ? esc(x) : x
        end
        args = (esc(a) for a in args)
        return :(add!($incirc, ($f($(args...)))...))
    end
end
```
It seems that after replacing `incirc` with `esc(incirc)`, literal instances of `incirc` are actually replaced by `esc(incirc)`. But if `incirc` is a symbol bound to `x` it is not wrapped in `esc`. So to find these unwrapped `incirc` and wrap them, we can't just do `incirc == x`, because the literal `incirc` will be wrapped. Solution: compare `esc(x)`  to `incirc` (which is actualy `esc(incirc)`.

This is my best guess about what is happening after debugging for a while.

**Comment by jlapeyre** [comment]
The following is simpler and also works
```julia
macro circ(incirc, ex)
    MacroTools.postwalk(ex) do x
        if !(@capture(x, f_(args__)) && f in GateList)
            return x == incirc ? esc(x) : x
        end
        newargs = (esc(a) for a in args)
        return :(add!($(esc(incirc)), ($f($(newargs...)))...))
    end
end
```
Using `newargs` is not necessary here. But, in general, rebinding a symbol to something new can cause trouble. As it did in with `incirc`.

**Comment by jlapeyre** [comment]
Back to the idea of using `getproperty`. (In fact you could use both `getproperty` and a macro). It might make sense to support a list of gates using `circ.gate(x,y)` notation. The user would have to edit such a list to add something, but maybe the macros could be used in these cases.  A requirement that I am considering in all of this is that dispatch happens during the AOT compilation, so that it is just as efficient as calling the function `addto!` directly.

I tested the following code, and found that dispatch happens at compile time. It depends on getting a few things right. For example, how you search the lists of gates. I tested it using dummy functions that just do some arithmetic. This is useful because the compiler can do constant propagate and you get `circ.h(3)` returning a number on 0ns. In other words, no computation is done at run time. A more realistic example, like pushing gates onto an Array will always take some time and can mask or complicate determining dispatch time.
```julia
module Amod

# struct A
#     data::Int
# end

struct A{T}
    data::T
end

A() = A([])

# The following makes a NamedTuple, like
# const GateMap = (sx = sx, h = h, u4 = u4, etc...)
const GateList = (:x, :sx, :y, :z, :h, :cx, :s, :sdg, :t, :tdg, :u, :u3, :rx, :ry, :rz, :rzx, :u4)
for sym in GateList
    @eval function $sym end
end
const GateMap = eval(Expr(:tuple, (:($x = $x) for x in GateList)...))

Base.getproperty(a::A, f::Symbol) = in(f, keys(GateMap)) ?
    (args...) -> addto!(a, getproperty(GateMap, f)(args...)) : getfield(a, f)

addto!(q::A, gate) = push!(q.data, gate)

struct U4
    x::Int
    y::Int
end

sx(x,y) = x + y
h(x) = x * 3
u4(x, y) = U4(x, y)
y(x) = x^2

end #module Amod

#using Amod: A
const y = Amod.A()
```

**Comment by jlapeyre** [comment]
Here is where the inefficiency enters. I change the code above to make the function executions fast, so that the lookup time is very visible:
```julia
module Amod

struct A{T}
    data::T
end

A() = A([])

const GateList = (:x, :sx, :y, :z, :h, :cx, :s, :sdg, :t, :tdg, :u, :u3, :rx, :ry, :rz, :rzx, :u4)
for sym in GateList
    @eval function $sym end
end
const GateMap = eval(Expr(:tuple, (:($x = $x) for x in GateList)...))

Base.getproperty(a::A, f::Symbol) = in(f, keys(GateMap)) ?
    (args...) -> addto!(a, getproperty(GateMap, f)(args...)) : getfield(a, f)

#addto!(q::A, gate) = push!(q.data, gate)
addto!(q::A, gate) = gate

struct U4
    x::Int
    y::Int
end

sx(x,y) = x + y
h(x) = x * 3
u4(x, y) = U4(x, y)
y(x) = x^2

end #module Amod

#using Amod: A
const y = Amod.A()
```

Now you can see the difference in these tests:
```julia
julia> @btime [Amod.addto!(y, Amod.h(3)) for i in 1:100];
  39.490 ns (1 allocation: 896 bytes)

julia> @btime [y.h(3) for i in 1:100];
  38.470 ns (1 allocation: 896 bytes)

julia> @btime [Amod.addto!(y, Amod.h(i)) for i in 1:100];
  40.297 ns (1 allocation: 896 bytes)

julia> @btime [y.h(i) for i in 1:100];
  4.753 μs (1 allocation: 896 bytes)
```
The last one is 100 times slower.

**Comment by jlapeyre** [comment]
The idea at the top of the previous comment seems to have worked. At least removed some fragility. If you use the code in the above comment, with the following change:
```julia
function Base.getproperty(a::A, f::Symbol)
    addfunc(ff) = (args...) -> addto!(a, ff(args...))
    if in(f, keys(GateMap))
        return addfunc(getproperty(GateMap, f))
    end
    getfield(a, f)
end
```
Then the efficiency is restored !
```julia
julia> @btime [Amod.addto!(y, Amod.h(i)) for i in 1:100];
  39.471 ns (1 allocation: 896 bytes)

julia> @btime [y.h(i) for i in 1:100];
  42.017 ns (1 allocation: 896 bytes)
```

**Comment by jlapeyre** [comment]
I threw together a repo [CBOO.jl](https://github.com/jlapeyre/CBOO.jl) that writes a `getproperty` . This would make it easier to try things out. Using it requires only a single line (other than importing `CBOO`.)  It would look like

```julia
@cboo_call QCircuit  addto! (x, sx, h, ...)
```
I did not yet try in `QuantumCircuits.jl`

**Comment by jlapeyre** [comment]
One thing I noticed about the `@gate` macro you referenced above. In the examples, you use it on single lines. But, you can use it on large blocks of code. Also, it can be written a bit more concisely. Here, I don't use `esc` at all, and it seems to work. There may be some situations that would force you to modify it:
```julia
macro qc(ex)
    return _qcirc(ex)
end

function _qcirc(ex)
    MacroTools.postwalk(ex) do x
        (@capture(x, f_.g_(args__))) || return x
        return :(add!($f, $g, $(args...)))
    end
end
```
It is useful to do the expression rewriting in a plain function as I did here. You can pass it expressions for debugging. (macroexpand does something similar.)   The following works:
```julia
struct Circ{T}
    data::Vector{T}
end

Circ() = Circ([])

function Base.show(io::IO, m::MIME"text/plain", circ::Circ)
    println(io, "Circ with data:")
    show(io, m, circ.data)
end

add!(circ::Circ, gate, args...) = (push!(circ.data, gate(args...)); circ)

# Restore original syntax in the generic case
add!(x, y, args...) = x.y(args...)
# Another option is the following
#add!(x, y, args...) = y(x, args...) # standard dot call meaning

x(i) = (:x, i)
h(i) = (:h, i)
cx(i,j) = (:cx, i, j)
rz(theta, i) = ((:rz,theta), i)

circ = Circ()
k = 100
fs(x) = x^2

@qc begin
    gs(x) = sqrt(x)
    circ.h(k).x(1)
    foreach(i -> circ.h(i), 1:4)
    foreach(i -> circ.cx(i[1],i[2]), zip(1:3, 2:4))
    circ.rz(fs(.5), 2)
    circ.rz(gs(.25), 1)
end
```

**Comment by rafal-pracht** [comment]
https://github.com/Adgnitio/QuantumCircuits.jl/issues/28#issuecomment-1125548043
We cannot escape the arguments in that way (I've tried this previously). If we did this, the code below doesn't work:
```julia
i = -1
j = -1
acirc = QCircuit(2)
@circ acirc begin
    i = 0
    j = 1

    x(i)
    h(j)
    cx(j, i)
end
```

But thanks to using if, in the macro definition, we can get the properties of circuits (for example number of qubits).

**Comment by rafal-pracht** [comment]
With [CBOO.jl](https://github.com/jlapeyre/CBOO.jl) it looks and works cool for me :) Thanks.

Could you release it as Julia's public package?

**Comment by rafal-pracht** [comment]
Do I understand you correctly? Do you think that I should restore the @gate and @circuit macro?

**Comment by jlapeyre** [comment]
No. Trying to rely on CBOO is best, I think.

The circuit macro, the one that lets you write just `h(i); cx(i,y)` etc. might still be useful. Maybe it looks more elegant in some situations? We would use the gate list that CBOO keeps for the macro. This would simplify thing.

**Comment by jlapeyre** [comment]
The package name has changed. This will be the registered package: https://github.com/jlapeyre/CBOOCall.jl
