### ISSUE TITLE
Allow `AbstractVector` for inputs

### ISSUE THREAD

**Issue by jlapeyre** [Adgnitio/QuantumCircuits.jl#3]
In this function
https://github.com/Adgnitio/QuantumCircuits.jl/blob/afa29aa8f488232d147ac4971e4b138da4eb9d5a/src/QCircuits/Circuit.jl#L284-L293
`qubits` and `cbits` are constrained to be the concrete type that you get from, say `[1,2,3]`. You can't pass `1:3`, for instance, which satisfies `1:3 isa AbstractVector{Int}`.  You might want to consider supporting such things.

 If you change the type annotation like this
```julia
function measure!(qc::QCircuit, qubits::AbstractVector{<:Integer}, cbits::AbstractVector{<:Integer})
```
then `1:3` is allowed. (And you had restricted both `qubits` and `cbits` to have the same concrete integer type which you may not really want to enforce)

There are a few other places where this happens as well, such as
https://github.com/Adgnitio/QuantumCircuits.jl/blob/afa29aa8f488232d147ac4971e4b138da4eb9d5a/src/QCircuits/Circuit.jl#L169-L172

Another thing: It's usually considered a good idea to support more general indexing even if you don't need it at the moment, for future proofing.  Usually this comes with no performance penalty. So, above you could do
```
    for i in eachindex(qubits)
        measure!(qc, qubits[i], cbits[i], false)
    end
```
Or even more generally
```
    for (i, j) in zip(eachindex(qubits), eachindex(cbits))
        measure!(qc, qubits[i], cbits[j], false)
    end
```
The latter would support, for instance, one of the arrays with indexing starting at zero. In fact, `PythonCall` and `PyCall` support Julia types that wrap Python sequences and use this zero-based indexing on the Julia side. Since qiskit in Julia will likely involve some Python interop, such situations may arise.

**Comment by rafal-pracht** [comment]
The issue should be fixed.
