### ISSUE TITLE
import vs using with Zygote

### ISSUE THREAD

**Issue by jlapeyre** [Adgnitio/QuantumCircuits.jl#46]
A fairly common opinion, which I share, is that in library code one should not do `using PackageA` (which is the same as Python's `from packagea import *`.)  Doing so makes it hard to see where imported libraries are being used. In particular, in `QuantumCircuits.jl` I am trying to find which symbols imported from `Zygote` are being used. But haven't been able to find out which. If you make relatively few calls of functions from Zygote, the approach I favor would be
```julia
import Zygote
```
Then, when you use a symbol from Zygote, you would fully qualify it. For example `Zygote.gradient(x,y,z)`.

An alternative is
```julia
using Zygote: gradient, another_func
```
Then, you could call `gradient` without qualification. Some people prefer this way. But, many, including myself prefer the first.

There is quite a bit of discussion of this topic on various forums. But, I don't find it explicitly in a style guide.

**Comment by rafal-pracht** [comment]
Ok, let's change this and use the first approach:
 ```julia
import Zygote
``` 
and then 
 ```julia
Zygote.gradient(x,y,z).
```

**Comment by jlapeyre** [comment]
I think the only use of Zygote in the source (not in ./test) is here
https://github.com/Adgnitio/QuantumCircuits.jl/blob/600b38ef6afb0d46b9ab6da8ab9d1f5740217aea/src/QML/CircuitOptimization.jl#L44

Here `'` is replaced by `adjoint`.  Of course, it has nothing to do with the adjoint. Replacing this by `Zygote.adjoint` would be confusing. If you look at the source to Zygote, it seems that `gradient(loss, params)[1]` is probably equivalent.
