### ISSUE TITLE
Possible typo in variable name

### ISSUE THREAD

**Issue by jlapeyre** [Adgnitio/QuantumCircuits.jl#47]
It looks like `i` is used in the loop, but `j` is not.

https://github.com/Adgnitio/QuantumCircuits.jl/blob/6383c1de4457c4ddef0ae51d10855bdf30ed5186/src/QCircuits/Circuit.jl#L288-L290

I think that if the two arrays have exactly the same indices, this would not cause an error.

**Comment by rafal-pracht** [comment]
Yes, this is a typo.
