### ISSUE TITLE
More abstract types in structs

### ISSUE THREAD

**Issue by jlapeyre** [Adgnitio/QuantumCircuits.jl#6]
You might see big performance boosts by fixing the things below.

I think this
https://github.com/Adgnitio/QuantumCircuits.jl/blob/afa29aa8f488232d147ac4971e4b138da4eb9d5a/src/QCircuits/Registers.jl#L27-L32
should be
```julia
mutable struct Cbit <: Bit
    index::Union{Int, Nothing}
    regIndex::Int

    Cbit(idx::Integer) = new(nothing, idx)
end
```
You might want to parameterize it like this
```julia
mutable struct Cbit{T<:Integer} <: Bit
    index::Union{T, Nothing}
    regIndex::T

    Cbit(idx::Integer) = new(nothing, idx)
end
```
But, I wouldn't do this unless you forsee a situation where this is useful.

Note that the other use of `Integer`, here `Cbit(idx::Integer) = new(nothing, idx)` is useful. It will coerce, say, a `BigInt` to an `Int` during construction.

Other places where I see this:
https://github.com/Adgnitio/QuantumCircuits.jl/blob/afa29aa8f488232d147ac4971e4b138da4eb9d5a/src/QCircuits/Registers.jl#L35-L37

In the following, it looks like you really do want to preserve the possibility of a different concrete type of integer
https://github.com/Adgnitio/QuantumCircuits.jl/blob/afa29aa8f488232d147ac4971e4b138da4eb9d5a/src/QCircuits/Graph.jl#L19-L20

In this case, instead of this
https://github.com/Adgnitio/QuantumCircuits.jl/blob/afa29aa8f488232d147ac4971e4b138da4eb9d5a/src/QCircuits/Graph.jl#L28-L39

I would do this, first remove `const IndexT = Integer`, then just make `IndexT` a parameter.
```julia
struct DirectedGraph{IndexT<:Integer}  # <:Integer is optional; for catching errors earlier, for instance.
    qubits::Int   # <---- Int not Integer
    start_nodes::Vector{IndexT}
    end_nodes::Vector{IndexT}
    vertices::Vector{QuantumGate}
    vertices_map::Dict{QuantumGate, IndexT}
    edges::Vector{Pair{IndexT, IndexT}}
    #sources::Vector{QuantumGate}
    #targets::Vector{QuantumGate}
    in_edges::Vector{Set{IndexT}}
    out_edges::Vector{Set{Pair{Int, IndexT}}}
end
```
`IndexT` will take values like `Int`, which will allow the compiler to optimize.
Or you may want this
```julia
struct DirectedGraph{T, IndexT}
    qubits::T
    start_nodes::Vector{IndexT}
    end_nodes::Vector{IndexT}
    vertices::Vector{QuantumGate}
    vertices_map::Dict{QuantumGate, IndexT}
    edges::Vector{Pair{IndexT, IndexT}}
    #sources::Vector{QuantumGate}
    #targets::Vector{QuantumGate}
    in_edges::Vector{Set{IndexT}}
    out_edges::Vector{Set{Pair{T, IndexT}}}
end
```
if you want to allow the type of `qubits` to vary as well. And I don't know if  the nodes of the graph in `out_edges::Vector{Set{Pair{T, IndexT}}}` are qubit indices or not.

Be careful here:
https://github.com/Adgnitio/QuantumCircuits.jl/blob/afa29aa8f488232d147ac4971e4b138da4eb9d5a/src/QCircuits/Graph.jl#L42-L50
Even if you use type parameters in the definition of `DirectedGraph`, and replace `IntegerT` by `Integer`, this constructor will work, but actually give you abstract types in the object created. This is because `Integer <: Integer` is true.
For example
```julia
julia> struct A{T<:Integer}
         n::Int
         x::Vector{T}
       end

julia> make_A(n) = A(n, Vector{Integer}(undef,0))  # Don't do this!
make_A (generic function with 1 method)

julia> make_A(3)
A{Integer}(3, Integer[])  # Not good. You almost certainly don't wan this

julia> A(3, Int[])
A{Int64}(3, Int64[])  # This is OK.

julia> make_A(n) = A(n, Vector{Int}(undef,0))  # <--- Instead, do this
make_A (generic function with 1 method)

julia> make_A(3)
A{Int64}(3, Int64[])
```

It is easy to find other places to avoid abstract types. But, here are some more.
https://github.com/Adgnitio/QuantumCircuits.jl/blob/afa29aa8f488232d147ac4971e4b138da4eb9d5a/src/QCircuits/Graph.jl#L74-L75

https://github.com/Adgnitio/QuantumCircuits.jl/blob/afa29aa8f488232d147ac4971e4b138da4eb9d5a/src/QCircuits/Graph.jl#L103

**Comment by rafal-pracht** [comment]
The issue should be fixed.
