### ISSUE TITLE
Allow more types as input

### ISSUE THREAD

**Issue by jlapeyre** [Adgnitio/QuantumCircuits.jl#9]
This line
https://github.com/Adgnitio/QuantumCircuits.jl/blob/fa10c8b8c25f160be368a86a938c39f8d0d3023c/src/QCircuits/Qiskit.jl#L118
would be better as `getQRegister(qc::QiskitCircuit, name::AbstractString) = qc.qRegs[name]`.

String manipulation functions and search functions usually return a `SubString` and this is then passed around. The modified version allows accepting `SubString`s.  The current version will not. This is a problem in the Julia ecosystem in general. There is something written on this by Jakob Nybo Nissen, but I can't find it at the moment.

**Comment by MozammilQ** [comment]
@rafal-pracht , please confirm if the suggested changes are welcome :)

**Comment by rafal-pracht** [comment]
@MozammilQ Yes, these changes are welcome. Could you do that?

**Comment by MozammilQ** [comment]
@rafal-pracht , please see if my PR #43 seems good to you :smile:

**Comment by MozammilQ** [comment]
> The current version will not. This is a problem in the Julia ecosystem in general. There is something written on this by Jakob Nybo Nissen, but I can't find it at the moment.

@jlapeyre , Is this the article you are talking about here?
This: https://viralinstruction.com/posts/badjulia/

**Comment by jlapeyre** [comment]
> Is this the article you are talking about here?
This: https://viralinstruction.com/posts/badjulia/

@MozammilQ Yes, this is the article.
